version: '3'

volumes:
  pg_data:
  static:
  media:

networks:
  internal_network:
    driver: bridge

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal_network

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal_network

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    env_file: .env
    volumes:
      - static:/frontend_static
    networks:
      - internal_network

  nginx:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - static:/var/html
      - media:/var/html/media
    depends_on:
      - backend
      - frontend
    networks:
      - internal_network
